### ISSUE TITLE
[CLOSED] - User end problem with his display - Add a link to the github.com repo, to encourage colloboration ideally in a prominent place.

### ISSUE THREAD

**Issue by jtmlis** [visualizingthefuture/visualizingthefuture.github.io#3]
Oh dear so sorry, this was an issue on my display, where a portion of the site cutoff. Very embarassing.

- [x] github public repo is not easily accessible. (however, i should of thought of trying the subdomain name on the github url)
- [x] website doesn't list both upcoming dates for Viz & Tell scheduled October 20th at 2pm est and Nov 17 at 2pm est.
- [x] Fellow profiles do not include contact information.
- [x] The mailing list, is not made prominent and easily accessible.

https://archive.org/compress/search-.-visualizing-the-future/formats=TEXT%20PDF&file=/search-.-visualizing-the-future.zip

**Comment by amzoss** [comment]
Don't be embarrassed at all! Our site does seem to show up a bit strangely on different displays, so while we haven't had much time to look at it yet, it's very important to us that the site works well. I'm sure we have some updates we can do that will help.
