### ISSUE TITLE
[SOLVED] - event to be listed via newsletter - Add Viz & tell 1 and 2

### ISSUE THREAD

**Issue by jtmlis** [visualizingthefuture/visualizingthefuture.github.io#7]
Hi I wasn't sure what type for format to post under, but since I started sharing this resource. I was hoping we could update the landing page with some details for the next events.

**Comment by jtmlis** [comment]
From the 2018-08-08-live-update.md

---
layout: post
title: Register for our October Viz and Tell
---
Our first Viz and Tell is coming up on **[October 20 at 2pm Eastern time (11am Pacific, 6pm UTC)](https://www.timeanddate.com/worldclock/converter.html?iso=20201020T180000&p1=tz_gmt&p2=179&p3=137&p4=136&p5=33&p6=37).** We are excited about building and maintaining active connections to the broad community of individuals teaching and using visualization in libraries.


Tune in to learn about:    
*	The goals of the grant
*	Grant activities and projects, like our resources for new visualization librarians and our instruction modules in progress
*	Upcoming opportunities to join together as a community interested in visualization in libraries
 
We will plan to leave extensive time for public q&a and discussion. We really want to know what the broader community is thinking and doing around data visualization in libraries.

Details:    
**Viz and Tell**    
Tuesday, October 20    
1pm to 2pm Eastern time | 11am to 12am Pacific time | 6pm to 7pm UTC time    

We hope you’ll join us to learn more about projects and our plans for the fall.

[Register for our September Live Update](https://forms.gle/wsPtYhWVuxudVLS59)

**Comment by amzoss** [comment]
Hi @jtm-lis,

Sorry, we're not quite ready to post the Viz and Tell on the home page! We want our webinar follow-up post to go out first. But we'll get to it shortly, I promise. If you'd like to help advertise, please share the link to our mailing list and/or website. We'll send out details about Viz and Tell registration a few weeks before the scheduled date, so people don't forget about it.

Best,
Angela

**Comment by jtmlis** [comment]
Okay great thank you for reaching out.
