### ISSUE TITLE
Can't archive the website via archive.org

### ISSUE THREAD

**Issue by jtmlis** [visualizingthefuture/visualizingthefuture.github.io#9]
I couldn't find the robots.txt, but anyway I don't know if this is local to my machine, but archiving the github.io website on the wayback machine returns an error.

https://web.archive.org/save/https://github.com/visualizingthefuture/examples-repository

The github.com urls work fine. 

archive.is is working fine, which is what leads me to believe it is the robots file.

**Comment by amzoss** [comment]
Closing because this issue seems to be about the examples repository, which is a different repo. Have copied it there.

https://github.com/visualizingthefuture/examples-repository/issues/118
